name: movie_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: 0.6.9
  dartz: ^0.9.2
  flushbar: ^1.10.4
  flutter_bloc: ^6.1.1
  flutter_icons: ^1.1.0
  flutter_svg: ^0.19.0
  freezed_annotation: ^0.12.0
  get_it: ^5.0.3
  http: ^0.12.2
  injectable: ^1.0.7
  json_annotation: ^3.1.1
  kt_dart: ^0.8.0
  lottie: ^0.7.0+1
  flutter_riverpod: 0.12.0
  cached_network_image: ^2.5.0
  devicelocale: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: 0.6.10
  build_runner: null
  freezed: ^0.12.6
  injectable_generator: ^1.0.7
  json_serializable: ^3.5.1

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
  fonts:
    - family: BN
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: MONOTON
      fonts:
        - asset: assets/fonts/Monoton-Regular.ttf